### ISSUE TITLE
Retirar banco que não possuem código.

### ISSUE THREAD

**Issue by lclpedro** [corenzan/bbdb#2]
Pra API ficar mais limpa, poderia retirar informações que não possuem código, isso ajudaria muito para validação de quem utiliza a API.

**Comment by haggen** [comment]
Oi @lclpedro. Ao invés de removê-los eu adicionei um parâmetro novo na URL: `compact` se passado com valor `true`, `yes`, `on`, ou `1` o retorno exclui bancos cujos códigos estão vazios. Espero que isso ajude!
